-- ============================================================
-- Cập nhật mô tả chi tiết cho sản phẩm
-- Chạy trong Supabase SQL Editor
-- ============================================================

UPDATE products SET description = v.new_desc FROM (VALUES
  ('iphone-15-pro-max-256gb', E'✦ Chip A17 Pro (3nm) – nhanh nhất trên smartphone, hỗ trợ ray tracing phần cứng.\n✦ Khung Titan cấp hàng không, nhẹ hơn thép 44%.\n✦ Camera 48MP ProRAW + Telephoto 5x quang học, quay video ProRes 4K/60fps.\n✦ Màn hình Super Retina XDR 6.7" ProMotion 120Hz, tối đa 2000 nits.\n✦ Pin 29 giờ phát video, sạc MagSafe 15W & USB-C 3.\n✦ Action Button tùy chỉnh, Dynamic Island.\n📌 Phù hợp: Người dùng chuyên nghiệp, nhiếp ảnh gia di động, game thủ mobile cao cấp.'),
  ('iphone-15-128gb', E'✦ Chip A16 Bionic – hiệu năng vượt trội mọi Android tầm trung.\n✦ Camera chính 48MP Photonic Engine, chụp đêm cực tốt.\n✦ Dynamic Island thay thế notch – hiển thị thông báo thông minh.\n✦ Cổng USB-C thay Lightning, tương thích phụ kiện phổ thông.\n✦ Màn hình Super Retina XDR 6.1", độ sáng 2000 nits ngoài trời.\n✦ Pin 20 giờ, hỗ trợ sạc nhanh 20W.\n📌 Phù hợp: Người dùng phổ thông muốn trải nghiệm iPhone tốt nhất trong tầm giá.'),
  ('samsung-galaxy-s24-ultra', E'✦ Snapdragon 8 Gen 3 – chip mạnh nhất Android 2024, AI on-device.\n✦ Bút S Pen tích hợp – viết tay, ghi chú, ký tài liệu.\n✦ Camera 200MP + zoom quang học 5x + zoom AI 100x.\n✦ Màn hình Dynamic AMOLED 2X 6.8", 120Hz, sáng 2600 nits.\n✦ Pin 5000mAh, sạc nhanh 45W, sạc không dây 15W.\n✦ Galaxy AI: phiên dịch cuộc gọi, tóm tắt văn bản, chỉnh sửa ảnh AI.\n📌 Phù hợp: Người dùng doanh nhân, sáng tạo nội dung, cần năng suất cao.'),
  ('samsung-galaxy-a55-5g', E'✦ Exynos 1480 (4nm) – hiệu năng gaming tốt trong tầm giá.\n✦ Camera 50MP OIS chống rung quang học – chụp đêm sắc nét.\n✦ Màn hình Super AMOLED 6.6" 120Hz, màu sắc sống động.\n✦ Pin 5000mAh + sạc nhanh 45W – đầy pin trong 1 tiếng.\n✦ Khung nhôm, mặt kính Corning Gorilla Glass Victus+.\n✦ 5G, Wi-Fi 6, Bluetooth 5.3.\n📌 Phù hợp: Sinh viên, người trẻ cần điện thoại đẹp, pin trâu, giá hợp lý.'),
  ('samsung-galaxy-s23-fe', E'✦ Snapdragon 8 Gen 1 – chip flagship 2022, còn rất mạnh.\n✦ Camera 50MP OIS + góc siêu rộng 12MP + telephoto 8MP.\n✦ Màn hình Dynamic AMOLED 6.4" 120Hz, 1200 nits.\n✦ Pin 4500mAh, sạc nhanh 25W.\n✦ Kính Corning Gorilla Glass 5, khung nhôm.\n✦ Tích hợp Galaxy AI từ One UI 6.1.\n📌 Phù hợp: Người muốn trải nghiệm Galaxy flagship với giá tầm trung.'),
  ('xiaomi-14-ultra', E'✦ Snapdragon 8 Gen 3 – chip Android mạnh nhất hiện tại.\n✦ Camera Leica Summilux 4 ống kính: 50MP + 50MP + 50MP + 50MP.\n✦ Cảm biến Sony LYT-900 1 inch – chụp đêm ngang DSLR.\n✦ Sạc siêu tốc 90W có dây + 80W không dây.\n✦ Màn hình LTPO AMOLED 6.73" 120Hz, 3000 nits.\n✦ Pin 5000mAh.\n📌 Phù hợp: Nhiếp ảnh gia di động, người mê công nghệ, cần camera tốt nhất thị trường.'),
  ('xiaomi-redmi-note-13-pro', E'✦ Snapdragon 7s Gen 2 – hiệu năng tốt cho gaming và đa nhiệm.\n✦ Camera 200MP – chụp ảnh cực kỳ chi tiết, zoom số ấn tượng.\n✦ Màn hình AMOLED cong 6.67" 120Hz, 1800 nits.\n✦ Pin 5100mAh, sạc siêu nhanh 67W.\n✦ Thiết kế mỏng 7.98mm, kính Gorilla Glass 5.\n📌 Phù hợp: Người yêu nhiếp ảnh smartphone muốn camera tốt với ngân sách vừa phải.'),
  ('iphone-14-128gb', E'✦ Chip A15 Bionic – vẫn mạnh hơn hầu hết Android flagship.\n✦ Camera Photonic Engine 12MP – cải thiện chụp đêm 2x.\n✦ Crash Detection & Emergency SOS vệ tinh.\n✦ Màn hình Super Retina XDR 6.1" 460ppi.\n✦ Pin 20 giờ phát video.\n📌 Phù hợp: Người dùng iPhone cũ muốn nâng cấp nhẹ, sinh viên cần iPhone bền bỉ.'),
  -- Laptop
  ('macbook-air-m2-8gb-256gb', E'✦ Chip M2 (8 CPU + 8 GPU) – nhanh hơn MacBook Air M1 40%.\n✦ Thiết kế siêu mỏng 11.3mm, nhẹ 1.24kg – không quạt tản nhiệt.\n✦ Màn hình Liquid Retina 13.6" 500 nits, P3 wide color.\n✦ Pin 18 giờ – cả ngày làm việc không cắm sạc.\n✦ MagSafe 2, 2x Thunderbolt/USB 4, Jack 3.5mm.\n✦ RAM 8GB Unified Memory, SSD NVMe tốc độ cao.\n📌 Phù hợp: Sinh viên, designer, người làm văn phòng cần laptop nhẹ, pin trâu.'),
  ('macbook-pro-m3-16gb-512gb', E'✦ Chip M3 Pro (11 CPU + 14 GPU) – hiệu năng chuyên nghiệp.\n✦ Màn hình Liquid Retina XDR 14.2" 1000 nits, ProMotion 120Hz.\n✦ RAM 18GB Unified Memory – xử lý video 4K, 3D mượt mà.\n✦ Pin 22 giờ.\n✦ 3x Thunderbolt 4, HDMI 2.1, SD card, MagSafe 3.\n✦ Âm thanh 6 loa Spatial Audio.\n📌 Phù hợp: Nhà phát triển phần mềm, video editor, kiến trúc sư, nhà thiết kế chuyên nghiệp.'),
  ('macbook-air-m3-15-inch', E'✦ Chip M3 (8 CPU + 10 GPU) – hiệu năng mạnh hơn M2 35%.\n✦ Màn hình Liquid Retina 15.3" lớn nhất dòng Air.\n✦ Siêu mỏng, nhẹ 1.51kg, không quạt.\n✦ Pin 18 giờ.\n✦ Hỗ trợ 2 màn hình ngoài đồng thời (khi đóng nắp).\n📌 Phù hợp: Người cần màn hình lớn nhưng vẫn mang đi công tác, content creator nhẹ.'),
  ('asus-zenbook-14-oled', E'✦ Intel Core Ultra 7 155H (Intel AI) – chip AI thế hệ mới nhất.\n✦ Màn hình OLED 2.8K 120Hz – màu sắc chuẩn xác tuyệt đối, đen tuyền.\n✦ RAM 16GB LPDDR5X, SSD 512GB PCIe 4.0.\n✦ Pin 75Wh, sạc nhanh 65W USB-C.\n✦ Thiết kế nhôm mỏng 14.9mm, nhẹ 1.2kg.\n📌 Phù hợp: Designer, người làm đồ họa cần màn hình OLED chuẩn màu, di chuyển nhiều.'),
  ('hp-pavilion-15-i5', E'✦ Intel Core i5-1235U (12th Gen) – xử lý tốt công việc văn phòng, lập trình.\n✦ RAM 8GB DDR4, SSD 512GB – khởi động nhanh, đa nhiệm tốt.\n✦ Màn hình FHD IPS 15.6" chống chói – mắt không mỏi khi làm việc dài.\n✦ Pin 8 giờ thực tế.\n✦ Bàn phím có đèn nền, webcam HD.\n📌 Phù hợp: Sinh viên, nhân viên văn phòng cần laptop phổ thông, giá tốt.'),
  ('asus-rog-strix-g16', E'✦ Intel Core i9-14900HX + RTX 4070 – combo gaming cực mạnh.\n✦ Màn hình QHD 165Hz 16" – hình ảnh sắc nét, mượt tuyệt đối.\n✦ RAM 16GB DDR5, SSD 1TB PCIe 4.0.\n✦ Hệ thống làm mát Tri-Fan Technology, tản nhiệt MUX Switch.\n✦ Bàn phím RGB per-key, loa Dolby Atmos.\n📌 Phù hợp: Game thủ hardcore, streamer cần laptop gaming mạnh nhất tầm giá.'),
  ('dell-xps-15-i7-16gb-512gb', E'✦ Intel Core i7-13700H + NVIDIA RTX 4060 – đủ mạnh cho cả việc lẫn chơi.\n✦ Màn hình OLED 3.5K cảm ứng 60Hz – đẹp nhất phân khúc Windows.\n✦ RAM 16GB LPDDR5, SSD 512GB PCIe 4.0.\n✦ Thiết kế nhôm/carbon, mỏng 18mm.\n✦ Thunderbolt 4, SD card, webcam IR.\n📌 Phù hợp: Kỹ sư, nhà thiết kế cần laptop premium vừa mỏng đẹp vừa có GPU rời.'),
  -- Tai nghe
  ('sony-wh-1000xm5', E'✦ Chống ồn Industry-leading – 8 mic, 2 chip xử lý âm thanh QN1 + V1.\n✦ LDAC Hi-Res Audio không dây – chất lượng âm thanh cao cấp.\n✦ Pin 30 giờ chống ồn, sạc nhanh 3 phút = 3 giờ.\n✦ Đàm thoại tự nhiên (Speak-to-Chat, Quick Attention).\n✦ Kết nối đa điểm – 2 thiết bị cùng lúc.\n📌 Phù hợp: Dân văn phòng, người đi máy bay, cần tập trung làm việc không bị phân tâm.'),
  ('sony-wh-1000xm4', E'✦ Chống ồn hàng đầu thế hệ trước – vẫn cực tốt.\n✦ LDAC + DSEE Extreme upscale nhạc số lên Hi-Res.\n✦ Pin 30 giờ, sạc nhanh 10 phút = 5 giờ.\n✦ Wearing detection tự tạm dừng khi tháo tai nghe.\n✦ Alexa + Google Assistant tích hợp.\n📌 Phù hợp: Người muốn tai nghe Sony cao cấp với giá tốt hơn XM5.'),
  ('airpods-pro-2nd-gen', E'✦ Chip H2 – chống ồn mạnh hơn XM5 theo Apple, xử lý 48.000 lần/giây.\n✦ Adaptive Transparency – nghe âm thanh xung quanh thông minh.\n✦ Spatial Audio cá nhân hóa theo hình tai.\n✦ Vỏ sạc USB-C, sạc không dây MagSafe.\n✦ Chống nước IP54 tai nghe + IP54 vỏ sạc.\n📌 Phù hợp: Người dùng iPhone muốn tai nghe TWS tốt nhất tích hợp hoàn hảo với hệ sinh thái Apple.'),
  ('airpods-max', E'✦ Driver 40mm tùy chỉnh – âm bass sâu, treble trong vắt.\n✦ Adaptive EQ tự động chỉnh âm theo con tai.\n✦ Chống ồn ANC + Transparency mode đẳng cấp.\n✦ Spatial Audio với head tracking – xem phim như rạp chiếu.\n✦ Vỏ nhôm anodized, đệm tai protein leather.\n📌 Phù hợp: Audiophile muốn tai nghe over-ear đỉnh cao trong hệ sinh thái Apple.'),
  ('jbl-tune-770nc', E'✦ ANC Adaptive chống ồn thích ứng theo môi trường.\n✦ Bluetooth 5.3, kết nối đa điểm 2 thiết bị.\n✦ Pin 70 giờ không ANC, 44 giờ có ANC.\n✦ Sạc nhanh USB-C: 5 phút = 3 giờ nghe.\n✦ Gập gọn, nhẹ 203g.\n📌 Phù hợp: Học sinh, sinh viên cần tai nghe chống ồn tốt giá rẻ, pin siêu trâu.'),
  ('razer-blackshark-v2-pro', E'✦ Driver TriForce Titanium 50mm – âm thanh gaming chi tiết, định vị chính xác.\n✦ Mic SuperCardioid có thể tháo rời – lọc tiếng ồn tốt khi stream.\n✦ THX Spatial Audio 7.1 không dây.\n✦ Pin 70 giờ, kết nối HyperSpeed 2.4GHz.\n✦ Đệm tai Memory Foam thoáng khí.\n📌 Phù hợp: Game thủ, streamer cần tai nghe gaming không dây chuyên nghiệp.'),
  ('samsung-galaxy-buds3-pro', E'✦ ANC 2 chiều + EQ thích ứng – chống ồn thế hệ mới của Samsung.\n✦ Thiết kế earstick mới, cánh định vị không rơi.\n✦ Bluetooth 5.4 + LE Audio, độ trễ cực thấp cho gaming.\n✦ Pin 30 giờ kể cả case, chống nước IP57.\n✦ Tích hợp Galaxy AI: phiên dịch trực tiếp qua tai nghe.\n📌 Phù hợp: Người dùng Samsung muốn TWS cao cấp tích hợp Galaxy AI.'),
  -- Màn hình
  ('lg-27gp850-b-27-inch', E'✦ IPS Nano 1440p 165Hz – chuẩn vàng cho gaming + làm việc sáng tạo.\n✦ 1ms GTG, G-Sync Compatible + FreeSync Premium – không xé hình, ghosting.\n✦ Độ phủ màu DCI-P3 98%, sRGB 135% – đủ màu cho design.\n✦ HDR400, độ sáng 350 nits.\n✦ USB-C 90W, 2x USB-A, DisplayPort + HDMI.\n📌 Phù hợp: Game thủ + designer cần một màn hình dùng được cho cả gaming và đồ họa.'),
  ('samsung-odyssey-g5-27-inch', E'✦ VA Curved 1000R 1440p 165Hz – đắm chìm trong game, màu đen sâu.\n✦ 1ms MPRT, AMD FreeSync Premium – cực mượt khi gaming.\n✦ HDR10, độ sáng 250 nits.\n✦ DisplayPort 1.2 + 2x HDMI 2.0.\n✦ Chân đế điều chỉnh nghiêng.\n📌 Phù hợp: Game thủ muốn màn cong immersive giá tốt.'),
  ('asus-proart-pa279cv', E'✦ IPS 4K UHD 3840x2160 60Hz – độ phân giải cực cao cho thiết kế.\n✦ 100% sRGB, 100% Rec.709, Delta E < 2 – màu chuẩn xác từ hộp.\n✦ USB-C 65W – cắm 1 dây vừa hiển thị vừa sạc laptop.\n✦ Calibration Report kèm theo hộp.\n✦ Chân đế 4 chiều: nghiêng, xoay, nâng, pivot.\n📌 Phù hợp: Nhiếp ảnh gia, video editor, kiến trúc sư cần màu hình chuẩn.'),
  -- Phụ kiện
  ('logitech-mx-master-3s', E'✦ Cảm biến Darkfield 8000 DPI – dùng được trên kính, đá cẩm thạch.\n✦ Cuộn MagSpeed điện từ – 1 vòng cuộn = 1000 dòng, siêu nhanh.\n✦ Kết nối Bolt USB + Bluetooth, đổi 3 thiết bị bằng 1 nút.\n✦ 7 nút tùy chỉnh + cuộn ngang.\n✦ Pin 70 ngày, sạc USB-C 1 phút = 3 giờ.\n📌 Phù hợp: Lập trình viên, designer, người làm office cần chuột năng suất cao.'),
  ('razer-deathadder-v3', E'✦ Cảm biến Focus Pro 30K DPI – tracking chính xác tuyệt đối.\n✦ Siêu nhẹ 59g – không mỏi tay khi chơi nhiều giờ.\n✦ Công tắc quang Razer – 90 triệu lần click, không double-click.\n✦ 6 nút tùy chỉnh Razer Synapse.\n✦ Dây Speedflex mềm như không dây.\n📌 Phù hợp: Game thủ FPS cần chuột nhẹ, chính xác cao.'),
  ('logitech-g-pro-x-superlight-2', E'✦ Cảm biến HERO 2 25K DPI – chính xác nhất Logitech từ trước đến nay.\n✦ Siêu nhẹ 60g – nhẹ nhất dòng G Pro.\n✦ LIGHTSPEED 2.4GHz – độ trễ 1ms, ngang có dây.\n✦ Pin 95 giờ, sạc USB-C.\n✦ 5 nút, không có đèn để tiết kiệm pin và giảm cân nặng.\n📌 Phù hợp: Game thủ esports chuyên nghiệp, cần chuột không dây đỉnh cao.'),
  ('samsung-t7-shield-1tb', E'✦ SSD di động tốc độ cao: đọc 1050MB/s, ghi 1000MB/s – nhanh gấp 10x USB thường.\n✦ Chống va đập MIL-STD-810G, chống bụi nước IP65.\n✦ Mã hóa AES 256-bit bảo vệ dữ liệu.\n✦ USB 3.2 Gen 2 (10Gbps).\n✦ Nhỏ gọn 98.5 x 59.2 x 13.5mm.\n📌 Phù hợp: Nhiếp ảnh gia, videographer cần backup dữ liệu nhanh khi đi thực địa.'),
  ('xiaomi-power-bank-30000mah', E'✦ Dung lượng 30000mAh – sạc điện thoại 7-8 lần, sạc laptop được.\n✦ Sạc nhanh 65W USB-C – có thể sạc MacBook, laptop 45W.\n✦ 3 cổng ra: 2x USB-A + 1x USB-C, sạc 3 thiết bị cùng lúc.\n✦ Hiển thị % pin LED.\n✦ Sạc vào 65W – đầy pin trong 1.5 giờ.\n📌 Phù hợp: Người hay đi xa, công tác, cần nguồn điện dự phòng lớn.')
) AS v(slug, new_desc)
WHERE products.slug = v.slug;

-- ============================================================
-- XONG! Mô tả sản phẩm đã được cập nhật chi tiết.
-- ============================================================
